#!/usr/bin/env node

/**
 * Setup script to create .env.local file with DATABASE_URL
 * Run with: node scripts/setup-env.js
 */

const fs = require('fs');
const path = require('path');

const ENV_FILE = path.join(__dirname, '..', '.env.local');
const DEFAULT_DATABASE_URL = 'postgresql://neondb_owner:npg_Gul7SO5geprM@ep-bold-recipe-agkib6vd-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require';

function main() {
  // Check if .env.local already exists
  if (fs.existsSync(ENV_FILE)) {
    console.log('✓ .env.local already exists');
    console.log(`  Location: ${ENV_FILE}`);
    
    // Read and display current DATABASE_URL (masked)
    try {
      const content = fs.readFileSync(ENV_FILE, 'utf8');
      const match = content.match(/DATABASE_URL=["']?([^"'\n]+)["']?/);
      if (match) {
        const url = match[1];
        // Mask the password in the URL
        const masked = url.replace(/:([^:@]+)@/, ':****@');
        console.log(`  Current DATABASE_URL: ${masked}`);
      }
    } catch (err) {
      // Ignore read errors
    }
    
    console.log('\nTo update it, delete .env.local and run this script again.');
    return;
  }

  // Create .env.local with default connection string
  const envContent = `# Database Connection String
# This file is automatically generated by setup-env.js
# DO NOT commit this file to version control

DATABASE_URL="${DEFAULT_DATABASE_URL}"

# Optional: Set to 'true' to disable SSL (only for local PostgreSQL without SSL)
# DATABASE_SSL_DISABLED=false
`;

  try {
    fs.writeFileSync(ENV_FILE, envContent, 'utf8');
    console.log('✓ Created .env.local file successfully!');
    console.log(`  Location: ${ENV_FILE}`);
    console.log(`  DATABASE_URL: ${DEFAULT_DATABASE_URL.replace(/:([^:@]+)@/, ':****@')}`);
    console.log('\nNext steps:');
    console.log('1. Restart your Next.js dev server (if running)');
    console.log('2. The dashboard should now connect to your Neon database');
    console.log('\nNote: If you need to use a different database URL, edit .env.local manually');
  } catch (error) {
    console.error('✗ Error creating .env.local file:');
    console.error(`  ${error.message}`);
    process.exit(1);
  }
}

main();

